# Autogenerated wrapper script for VLFeat_jll for aarch64-apple-darwin
export libvl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("VLFeat")
JLLWrappers.@declare_library_product(libvl, "@rpath/libvl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libvl,
        "lib/libvl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
