# Autogenerated wrapper script for VLFeat_jll for i686-w64-mingw32
export libvl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("VLFeat")
JLLWrappers.@declare_library_product(libvl, "libvl.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libvl,
        "bin\\libvl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
